const OFFICIAL_ABILITIES = {
  assassin: 'Once per game, at night*, choose a player: they die, even if for some reason they could not.',
  artist: 'Once per game, during the day, privately ask the Storyteller any yes/no question.',
  barber: 'If you died today or tonight, the Demon may choose 2 players (not another Demon) to swap characters.',
  baron: 'There are extra Outsiders in play. [+2 Outsiders]',
  butler: 'Each night, choose a player (not yourself): tomorrow, you may only vote if they are voting too.',
  cerenovus: 'Each night, choose a player & a good character: they are "mad" they are this character tomorrow, or might be executed.',
  chambermaid: 'Each night, choose 2 alive players (not yourself): you learn how many woke tonight due to their ability.',
  chef: 'You start knowing how many pairs of evil players there are.',
  clockmaker: 'You start knowing how many steps from the Demon to its nearest Minion.',
  courtier: 'Once per game, at night, choose a character: they are drunk for 3 nights & 3 days.',
  devils_advocate: 'Each night, choose a living player (different to last night): if executed tomorrow, they don\'t die.',
  dreamer: 'Each night, choose a player (not yourself or Travellers): you learn 1 good & 1 evil character, 1 of which is correct.',
  drunk: 'You do not know you are the Drunk. You think you are a Townsfolk character, but you are not.',
  empath: 'Each night, you learn how many of your 2 alive neighbours are evil.',
  evil_twin: 'You & an opposing player know each other. If the good player is executed, evil wins. Good can\'t win if you both live.',
  exorcist: 'Each night*, choose a player (different to last night): the Demon, if chosen, learns who you are then doesn\'t wake tonight.',
  fang_gu: 'Each night*, choose a player: they die. The 1st Outsider this kills becomes an evil Fang Gu & you die instead. [+1 Outsider]',
  flowergirl: 'Each night*, you learn if a Demon voted today.',
  fool: 'The first time you die, you don\'t.',
  fortune_teller: 'Each night, choose 2 players: you learn if either is a Demon. There is a good player that registers as a Demon to you.',
  gambler: 'Each night*, choose a player & guess their character: if you guess wrong, you die.',
  godfather: 'You start knowing which Outsiders are in play. If 1 died today, choose a player tonight: they die. [-1 or +1 Outsider]',
  goon: 'Each night, the 1st player to choose you with their ability is drunk until dusk. You become their alignment.',
  gossip: 'Each day, you may make a public statement. Tonight, if it was true, a player dies.',
  grandmother: 'You start knowing a good player & their character. If the Demon kills them, you die too.',
  imp: 'Each night*, choose a player: they die. If you kill yourself this way, a Minion becomes the Imp.',
  innkeeper: 'Each night*, choose 2 players: they can\'t die tonight, but 1 is drunk until dusk.',
  investigator: 'You start knowing that 1 of 2 players is a particular Minion.',
  juggler: 'On your 1st day, publicly guess up to 5 players\' characters. That night, you learn how many you got correct.',
  klutz: 'When you learn that you died, publicly choose 1 alive player: if they are evil, your team loses.',
  librarian: 'You start knowing that 1 of 2 players is a particular Outsider. (Or that zero are in play.)',
  lunatic: 'You think you are a Demon, but you are not. The Demon knows who you are & who you choose at night.',
  mastermind: 'If the Demon dies by execution (ending the game), play for 1 more day. If a player is then executed, their team loses.',
  mathematician: 'Each night, you learn how many players\' abilities worked abnormally (since dawn) due to another character\'s ability.',
  mayor: 'If only 3 players live & no execution occurs, your team wins. If you die at night, another player might die instead.',
  minstrel: 'When a Minion dies by execution, all other players (except Travellers) are drunk until dusk tomorrow.',
  monk: 'Each night*, choose a player (not yourself): they are safe from the Demon tonight.',
  moonchild: 'When you learn that you died, publicly choose 1 alive player. Tonight, if they are good, they die.',
  mutant: 'If you are "mad" about being an Outsider, you might be executed.',
  no_dashii: 'Each night*, choose a player: they die. Your 2 Townsfolk neighbours are poisoned.',
  oracle: 'Each night*, you learn how many dead players are evil.',
  pacifist: 'Executed good players might not die.',
  philosopher: 'Once per game, at night, choose a good character: gain that ability. If this character is in play, they are drunk.',
  pit_hag: 'Each night*, choose a player & a character they become (if not in play). If a Demon is made, deaths tonight are arbitrary.',
  po: 'Each night*, you may choose a player: they die. If your last choice was no-one, choose 3 players tonight.',
  poisoner: 'Each night, choose a player: they are poisoned tonight and tomorrow day.',
  professor: 'Once per game, at night*, choose a dead player: if they are a Townsfolk, they are resurrected.',
  pukka: 'Each night, choose a player: they are poisoned. The previously poisoned player dies then becomes healthy.',
  ravenkeeper: 'If you die at night, you are woken to choose a player: you learn their character.',
  recluse: 'You might register as evil & as a Minion or Demon, even if dead.',
  sage: 'If the Demon kills you, you learn that it is 1 of 2 players.',
  sailor: 'Each night, choose an alive player: either you or they are drunk until dusk. You can\'t die.',
  saint: 'If you die by execution, your team loses.',
  savant: 'Each day, you may visit the Storyteller to learn 2 things in private: 1 is true & 1 is false.',
  scarlet_woman: 'If there are 5 or more players alive & the Demon dies, you become the Demon. (Travellers don\'t count.)',
  seamstress: 'Once per game, at night, choose 2 players (not yourself): you learn if they are the same alignment.',
  shabaloth: 'Each night*, choose 2 players: they die. A dead player you chose last night might be regurgitated.',
  slayer: 'Once per game, during the day, publicly choose a player: if they are the Demon, they die.',
  snake_charmer: 'Each night, choose an alive player: a chosen Demon swaps characters & alignments with you & is then poisoned.',
  soldier: 'You are safe from the Demon.',
  spy: 'Each night, you see the Grimoire. You might register as good & as a Townsfolk or Outsider, even if dead.',
  sweetheart: 'When you die, 1 player is drunk from now on.',
  tea_lady: 'If both your alive neighbours are good, they can\'t die.',
  tinker: 'You might die at any time.',
  town_crier: 'Each night*, you learn if a Minion nominated today.',
  undertaker: 'Each night*, you learn which character died by execution today.',
  vigormortis: 'Each night*, choose a player: they die. Minions you kill keep their ability & poison 1 Townsfolk neighbour. [-1 Outsider]',
  virgin: 'The 1st time you are nominated, if the nominator is a Townsfolk, they are executed immediately.',
  vortox: 'Each night*, choose a player: they die. Townsfolk abilities yield false info. Each day, if no-one is executed, evil wins.',
  washerwoman: 'You start knowing that 1 of 2 players is a particular Townsfolk.',
  witch: 'Each night, choose a player: if they nominate tomorrow, they die. If only 3 players live, you lose this ability.',
  zombuul: 'Each night*, if no-one died today, choose a player: they die. The 1st time you die, you live but register as dead.'
}

function applyOfficialAbility(role) {
  return {
    ...role,
    ability: OFFICIAL_ABILITIES[role.id] || role.ability
  }
}

module.exports = {
  OFFICIAL_ABILITIES,
  applyOfficialAbility
}
